spring.application.name=demo
server.port=${PORT:8080}
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# PostgreSQL Database Configuration
# JDBC URL for the PostgreSQL database
spring.datasource.url=jdbc:postgresql://localhost:5432/your_database_name
# Database username
spring.datasource.username=your_username
# Database password
spring.datasource.password=your_password
# Database driver class name
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA and Hibernate Configuration
# Automatically update the database schema (use 'validate' or migration tools for production)
spring.jpa.hibernate.ddl-auto=update
# Show SQL queries executed by Hibernate (useful for debugging)
spring.jpa.show-sql=true
# Specify the dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# S3 Configuration
aws.accessKeyId=minioadmin
aws.secretKey=minioadmin
aws.s3.bucket=alerts
aws.s3.endpoint=http://localhost:9000

# Keycloak Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8181/realms/master
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
master.user.email=master@droidevs.com
master.user.password=MasterPassword123
master.user.firstname=Master
master.user.lastname=User
